# Sh script to generate requirements.txt file from py file generated by nbconvert
# install pipreqs
pip install pipreqs
# install nbconvert
pip install nbconvert
# convert ipynb to py
jupyter nbconvert --to script *.ipynb
# generate requirements.txt
pipreqs . --force
# remove py file
rm *.py

